### ISSUE TITLE
the tree node should be collapsed when you start

### ISSUE THREAD

**Issue by ideadBunny** [AnidemDex/Godot-DragNDropNodes#3]
![image](https://github.com/user-attachments/assets/94dffd3f-8835-427e-9b5b-6903418433a3)

it is like this when you open the project i think it will be better if the tree is collapsed not expanded

it should be like this  

![image](https://github.com/user-attachments/assets/8bd6fc2c-a581-49f7-ac33-e54e407ecaeb)

**Comment by AnidemDex** [comment]
I think is fixed now by #2 ?

**Comment by ideadBunny** [comment]
yeah @0whokarez0 already told it is already fixed

**Comment by AnidemDex** [comment]
Is already merged 🥳
